name: hiveplotter
dependencies:
- decorator=4.0.4=py35_0
- freetype=2.5.5=0
- geos=3.3.3=0
- jpeg=8d=0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libtiff=4.0.6=0
- networkx=1.10=py35_0
- nose=1.3.7=py35_0
- numpy=1.10.1=py35_0
- openblas=0.2.14=3
- openssl=1.0.2e=0
- pillow=3.0.0=py35_1
- pip=8.0.1=py35_0
- python=3.5.1=0
- readline=6.2=2
- setuptools=19.4=py35_0
- shapely=1.5.11=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - cairocffi==0.7.2
  - cycler==0.9.0
  - ipython==4.0.0
  - ipython-genutils==0.1.0
  - matplotlib==1.5.0
  - path.py==8.1.2
  - pexpect==4.0.1
  - pickleshare==0.5
  - ptyprocess==0.5
  - pycparser==2.14
  - pyparsing==2.0.5
  - python-dateutil==2.4.2
  - pytz==2015.7
  - pyx==0.14.1
  - simplegeneric==0.8.1
  - six==1.10.0
  - traitlets==4.0.0
  - virtualenv==13.1.2

